package dev.kennurken.tutorbot.task.event;

public enum TaskEventType {
    TASK_CREATED,
    TASK_SCHEDULED,
    TASK_NOTIFIED,
    TASK_STARTED,
    TASK_COMPLETION_REPORTED,
    TASK_COMPLETED,
    VERIFICATION_STARTED,
    VERIFICATION_PASSED,
    VERIFICATION_FAILED,
    VERIFICATION_UNCERTAIN,
    VERIFICATION_EXPIRED,
    TASK_MISSED,
    TASK_SKIPPED,
    TASK_RESCHEDULED,
    TASK_CANCELLED,
    CONSEQUENCE_APPLIED,
    REMINDER_SENT
}
